FROM python:3.9
WORKDIR /app/frontend
COPY requirements.txt /app/frontend
RUN pip install -r requirements.txt
COPY . /app/frontend 
EXPOSE 3000
CMD python /app/backend/manage.py runserver 0.0.0.0:3000
